version: "3.8"

services:
  uwsgi:
    image: intelowlproject/intelowl:${REACT_APP_INTELOWL_VERSION}
    container_name: intelowl_uwsgi
    volumes:
      - ../configuration/intel_owl.ini:/etc/uwsgi/sites/intel_owl.ini
      - ../configuration:/opt/deploy/intel_owl/configuration
      - generic_logs:/var/log/intel_owl
      - static_content:/opt/deploy/intel_owl/static
      - shared_files:/opt/deploy/files_required
    entrypoint:
      - ./docker/entrypoints/uwsgi.sh
    expose:
      - "8001"
    env_file:
      - env_file_app
      - .env
    environment:
      - BROKER_URL=redis://redis:6379/1
      - WEBSOCKETS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8001 || exit 1"]
      interval: 5s
      timeout: 2s
      start_period: 300s
      retries: 2

  daphne:
    image: intelowlproject/intelowl:${REACT_APP_INTELOWL_VERSION}
    container_name: intelowl_daphne
    restart: unless-stopped
    volumes:
      - generic_logs:/var/log/intel_owl
      - shared_files:/opt/deploy/files_required
    entrypoint:
      - ./docker/entrypoints/daphne.sh
    expose:
      - "8011"
    env_file:
      - env_file_app
    environment:
      - BROKER_URL=redis://redis:6379/1
      - WEBSOCKETS_URL=redis://redis:6379/0
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8011 || exit 1"]
      interval: 5s
      timeout: 2s
      start_period: 2s
      retries: 6
    depends_on:
      uwsgi:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    image: intelowlproject/intelowl_nginx:${REACT_APP_INTELOWL_VERSION}
    container_name: intelowl_nginx
    restart: unless-stopped
    volumes:
      - ../configuration/nginx/websocket.conf:/etc/nginx/websocket.conf
      - ../configuration/nginx/errors.conf:/etc/nginx/errors.conf
      - ../configuration/nginx/http.conf:/etc/nginx/conf.d/default.conf
      - ../configuration/nginx/locations.conf:/etc/nginx/locations.conf
      - nginx_logs:/var/log/nginx
      - static_content:/var/www/static
    depends_on:
      uwsgi:
        condition: service_healthy
      daphne:
        condition: service_healthy
    ports:
      - "80:80"

  celery_beat:
    image: intelowlproject/intelowl:${REACT_APP_INTELOWL_VERSION}
    container_name: intelowl_celery_beat
    restart: unless-stopped
    volumes:
      - ../configuration:/opt/deploy/intel_owl/configuration
      - generic_logs:/var/log/intel_owl
      - shared_files:/opt/deploy/files_required
    entrypoint:
      - ./docker/entrypoints/celery_beat.sh
    env_file:
      - env_file_app
    environment:
      - BROKER_URL=redis://redis:6379/1
      - WEBSOCKETS_URL=redis://redis:6379/0
    depends_on:
      uwsgi:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      disable: true

  celery_worker_default:
    image: intelowlproject/intelowl:${REACT_APP_INTELOWL_VERSION}
    container_name: intelowl_celery_worker_default
    restart: unless-stopped
    stop_grace_period: 3m
    volumes:
      - ../configuration:/opt/deploy/intel_owl/configuration
      - generic_logs:/var/log/intel_owl
      - shared_files:/opt/deploy/files_required
    entrypoint:
      - ./docker/entrypoints/celery_default.sh
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - env_file_app
    environment:
      - BROKER_URL=redis://redis:6379/1
      - WEBSOCKETS_URL=redis://redis:6379/0
    depends_on:
      uwsgi:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      disable: true

  postgres:
    image: library/postgres:16-alpine
    container_name: intelowl_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env_file_postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 2s
      retries: 6
      start_period: 3s

  redis:
    image: library/redis:6.2.7-alpine
    container_name: intelowl_redis
    hostname: redis
    restart: unless-stopped
    volumes:
      - generic_logs:/var/log/intel_owl
    expose:
      - "6379"
    healthcheck:
      test: test $$(redis-cli -h '127.0.0.1' ping) = 'PONG'

  bbot_analyzer:
    build:
      context: ../integrations/bbot
      dockerfile: Dockerfile
    image: intelowlproject/intelowl_bbot_analyzer:test
    depends_on:
      - uwsgi

  cyberchef-server:
    build:
      context: ../integrations/cyberchef
      dockerfile: Dockerfile
    image: intelowlproject/cyberchef:test
    depends_on:
      - uwsgi

  malware_tools_analyzers:
    build:
      context: ../integrations/malware_tools_analyzers
      dockerfile: Dockerfile
    image: intelowlproject/intelowl_malware_tools_analyzers:test
    depends_on:
      - uwsgi

  nuclei_analyzer:
    build:
      context: ../integrations/nuclei_analyzer
      dockerfile: Dockerfile
    image: intelowlproject/nuclei_analyzer:test
    depends_on:
      - uwsgi

  pcap_analyzers:
    build:
      context: ../integrations/pcap_analyzers
      dockerfile: Dockerfile
    image: intelowlproject/intelowl_pcap_analyzers:test
    depends_on:
      - uwsgi

  phishing_analyzers:
    build:
      context: ../integrations/phishing_analyzers
      dockerfile: Dockerfile
    image: intelowlproject/intelowl_phishing_analyzers:test
    depends_on:
      - uwsgi

  phoneinfoga:
    image: sundowndev/phoneinfoga:v2.11.0
    depends_on:
      - uwsgi

  thug:
    build:
      context: ../integrations/thug
      dockerfile: Dockerfile
    image: intelowlproject/intelowl_thug:test
    depends_on:
      - uwsgi

  tor_analyzers:
    build:
      context: ../integrations/tor_analyzers
      dockerfile: Dockerfile
    image: intelowlproject/intelowl_tor_analyzers:test
    depends_on:
      - uwsgi

volumes:
  postgres_data:
  nginx_logs:
  generic_logs:
  static_content:
  shared_files:
